"""update lead assigned_to to reference employees

Revision ID: 44f445f22b32
Revises: 47477c3e010c
Create Date: 2025-04-26 16:31:06.360431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f445f22b32'
down_revision: Union[str, None] = '47477c3e010c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('leads_assigned_to_fkey', 'leads', type_='foreignkey')
    op.drop_constraint('leads_client_id_fkey', 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'employees', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leads', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key('leads_client_id_fkey', 'leads', 'clients', ['client_id'], ['id'])
    op.create_foreign_key('leads_assigned_to_fkey', 'leads', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###
