"""add client_id to leads table

Revision ID: 47477c3e010c
Revises: 8d7f1688909e
Create Date: 2025-04-26 15:30:33.991167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47477c3e010c'
down_revision: Union[str, None] = '8d7f1688909e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'client_id')
    # ### end Alembic commands ###
