"""update document attendance milestone models

Revision ID: 63e6680f6d32
Revises: d892642e90b1
Create Date: 2024-03-19 12:34:56.789012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Enum
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '63e6680f6d32'
down_revision: Union[str, None] = 'd892642e90b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum types if they don't exist
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'attendancestatus') THEN
                CREATE TYPE attendancestatus AS ENUM ('present', 'absent', 'late', 'half_day', 'on_leave');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'documenttype') THEN
                CREATE TYPE documenttype AS ENUM ('resume', 'contract', 'id_proof', 'certificate', 'other');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'milestonestatus') THEN
                CREATE TYPE milestonestatus AS ENUM ('pending', 'in_progress', 'completed', 'cancelled');
            END IF;
        END$$;
    """)

    # Add updated_at columns if they don't exist
    for table in ['attendance', 'documents', 'milestones']:
        op.execute(f"""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = '{table}' AND column_name = 'updated_at'
                ) THEN
                    ALTER TABLE {table} ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
                END IF;
            END$$;
        """)

    # Update attendance status
    op.execute("UPDATE attendance SET status = 'present' WHERE status NOT IN ('present', 'absent', 'late', 'half_day', 'on_leave')")
    op.alter_column('attendance', 'status',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Enum('present', 'absent', 'late', 'half_day', 'on_leave', name='attendancestatus'),
                    postgresql_using='status::attendancestatus',
                    nullable=False)

    # Update document file_type
    op.execute("UPDATE documents SET file_type = 'other' WHERE file_type NOT IN ('resume', 'contract', 'id_proof', 'certificate', 'other')")
    op.alter_column('documents', 'file_type',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Enum('resume', 'contract', 'id_proof', 'certificate', 'other', name='documenttype'),
                    postgresql_using='file_type::documenttype',
                    nullable=False)

    # Update milestone status
    op.execute("UPDATE milestones SET status = 'pending' WHERE status NOT IN ('pending', 'in_progress', 'completed', 'cancelled')")
    op.alter_column('milestones', 'status',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='milestonestatus'),
                    postgresql_using='status::milestonestatus',
                    nullable=False)

    # Drop uploaded_by column and its foreign key if they exist
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'documents' AND column_name = 'uploaded_by'
            ) THEN
                ALTER TABLE documents DROP COLUMN uploaded_by CASCADE;
            END IF;
        END$$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_employee_attendance_date', 'attendance', ['employee_id', 'date'])
    op.alter_column('documents', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Convert enum columns back to varchar
    for table, column in [
        ('attendance', 'status'),
        ('documents', 'file_type'),
        ('milestones', 'status')
    ]:
        op.alter_column(table, column,
                       existing_type=sa.Enum,
                       type_=sa.VARCHAR(),
                       nullable=False)

    # Drop updated_at columns
    for table in ['attendance', 'documents', 'milestones']:
        op.execute(f"ALTER TABLE {table} DROP COLUMN IF EXISTS updated_at")

    # Drop enum types if they exist
    op.execute("""
        DO $$
        BEGIN
            DROP TYPE IF EXISTS attendancestatus;
            DROP TYPE IF EXISTS documenttype;
            DROP TYPE IF EXISTS milestonestatus;
        END$$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_employee_attendance_date', 'attendance', type_='unique')
    # ### end Alembic commands ###
