"""fix task user relationships

Revision ID: 66a854ceaa7d
Revises: aa6f63a0efff
Create Date: 2025-04-26 18:24:09.636096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a854ceaa7d'
down_revision: Union[str, None] = 'aa6f63a0efff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
