"""Change employee_feedbacks FKs to employees table

Revision ID: 7927607feffd
Revises: 66a854ceaa7d
Create Date: 2025-04-26 22:38:11.210908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7927607feffd'
down_revision: Union[str, None] = '66a854ceaa7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Keep foreign keys pointing to users table
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
