"""update_employee_feedback_foreign_keys

Revision ID: 7bd24338dfdb
Revises: aef3064e94c7
Create Date: 2025-04-30 10:08:10.437195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd24338dfdb'
down_revision: Union[str, None] = 'aef3064e94c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
