"""update_employee_feedback_from_id_to_users

Revision ID: aef3064e94c7
Revises: 6a2ceac12b66
Create Date: 2025-04-29 19:08:42.899623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aef3064e94c7'
down_revision: Union[str, None] = '6a2ceac12b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_service_documents_id', table_name='client_service_documents')
    op.drop_table('client_service_documents')
    op.drop_index('ix_client_interactions_id', table_name='client_interactions')
    op.drop_table('client_interactions')
    op.drop_index('ix_client_documents_id', table_name='client_documents')
    op.drop_table('client_documents')
    op.drop_index('ix_client_services_id', table_name='client_services')
    op.drop_table('client_services')
    op.drop_constraint('employee_feedbacks_from_employee_id_fkey', 'employee_feedbacks', type_='foreignkey')
    op.drop_constraint('employee_feedbacks_to_employee_id_fkey', 'employee_feedbacks', type_='foreignkey')
    op.create_foreign_key(None, 'employee_feedbacks', 'users', ['from_employee_id'], ['id'])
    op.create_foreign_key(None, 'employee_feedbacks', 'users', ['to_employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_feedbacks', type_='foreignkey')
    op.drop_constraint(None, 'employee_feedbacks', type_='foreignkey')
    op.create_foreign_key('employee_feedbacks_to_employee_id_fkey', 'employee_feedbacks', 'employees', ['to_employee_id'], ['id'])
    op.create_foreign_key('employee_feedbacks_from_employee_id_fkey', 'employee_feedbacks', 'employees', ['from_employee_id'], ['id'])
    op.create_table('client_services',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('client_services_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('monthly_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='client_services_client_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='client_services_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_client_services_id', 'client_services', ['id'], unique=False)
    op.create_table('client_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['client_services.id'], name='client_documents_service_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='client_documents_uploaded_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='client_documents_pkey')
    )
    op.create_index('ix_client_documents_id', 'client_documents', ['id'], unique=False)
    op.create_table('client_interactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interaction_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='client_interactions_created_by_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['client_services.id'], name='client_interactions_service_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='client_interactions_pkey')
    )
    op.create_index('ix_client_interactions_id', 'client_interactions', ['id'], unique=False)
    op.create_table('client_service_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['client_services.id'], name='client_service_documents_service_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='client_service_documents_uploaded_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='client_service_documents_pkey')
    )
    op.create_index('ix_client_service_documents_id', 'client_service_documents', ['id'], unique=False)
    # ### end Alembic commands ###
