"""update task employee relationship

Revision ID: 409f3da0c492
Revises: d3226113ff6b
Create Date: 2025-04-21 17:59:43.486329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409f3da0c492'
down_revision: Union[str, None] = 'd3226113ff6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attendance_employee_id_fkey', 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('employees', 'salary',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_constraint('milestones_employee_id_fkey', 'milestones', type_='foreignkey')
    op.create_foreign_key(None, 'milestones', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tasks_assigned_to_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'employees', ['assigned_to'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_assigned_to_fkey', 'tasks', 'users', ['assigned_to'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.create_foreign_key('milestones_employee_id_fkey', 'milestones', 'employees', ['employee_id'], ['id'])
    op.alter_column('employees', 'salary',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key('attendance_employee_id_fkey', 'attendance', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###
