"""add uploader_id to documents

Revision ID: 48f38c2c4fbe
Revises: eda419a84d6b
Create Date: 2025-04-23 11:45:48.787399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f38c2c4fbe'
down_revision: Union[str, None] = 'eda419a84d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploader_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['uploader_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'uploader_id')
    # ### end Alembic commands ###
