"""add folder_id to documents

Revision ID: 838d81288ea1
Revises: 48f38c2c4fbe
Create Date: 2025-04-23 11:49:23.050955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838d81288ea1'
down_revision: Union[str, None] = '48f38c2c4fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'document_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'folder_id')
    # ### end Alembic commands ###
