"""Add employee related tables

Revision ID: c7e80fdcdb09
Revises: 02d0b77f83ec
Create Date: 2025-04-23 11:38:43.945053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7e80fdcdb09'
down_revision: Union[str, None] = '02d0b77f83ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('name', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('type', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('url', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('upload_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('documents', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('documents_uploaded_by_fkey', 'documents', type_='foreignkey')
    op.drop_constraint('documents_folder_id_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'title')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'description')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'folder_id')
    op.drop_column('documents', 'uploaded_by')
    op.add_column('milestones', sa.Column('achieved_date', sa.Date(), nullable=False))
    op.add_column('milestones', sa.Column('type', sa.String(), nullable=False))
    op.drop_column('milestones', 'status')
    op.drop_column('milestones', 'date')
    op.add_column('tasks', sa.Column('assigned_date', sa.Date(), nullable=False))
    op.add_column('tasks', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::taskstatus"))
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::taskpriority"))
    op.drop_constraint('tasks_assigned_by_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_assigned_to_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'tags')
    op.drop_column('tasks', 'comments')
    op.drop_column('tasks', 'assigned_by')
    op.drop_column('tasks', 'assigned_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('assigned_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_assigned_to_fkey', 'tasks', 'employees', ['assigned_to'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tasks_assigned_by_fkey', 'tasks', 'users', ['assigned_by'], ['id'])
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::taskpriority"))
    op.alter_column('tasks', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::taskstatus"))
    op.drop_column('tasks', 'employee_id')
    op.drop_column('tasks', 'assigned_date')
    op.add_column('milestones', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('milestones', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('milestones', 'type')
    op.drop_column('milestones', 'achieved_date')
    op.add_column('documents', sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('folder_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.create_foreign_key('documents_folder_id_fkey', 'documents', 'document_folders', ['folder_id'], ['id'])
    op.create_foreign_key('documents_uploaded_by_fkey', 'documents', 'users', ['uploaded_by'], ['id'])
    op.alter_column('documents', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('documents', 'upload_date')
    op.drop_column('documents', 'url')
    op.drop_column('documents', 'type')
    op.drop_column('documents', 'name')
    # ### end Alembic commands ###
