"""update_tasks_table

Revision ID: d3226113ff6b
Revises: 82fc4b7c615f
Create Date: 2025-04-19 16:01:58.213057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3226113ff6b'
down_revision: Union[str, None] = '82fc4b7c615f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_id', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index('ix_folders_id', table_name='folders')
    op.drop_table('folders')
    op.create_index(op.f('ix_employee_feedbacks_id'), 'employee_feedbacks', ['id'], unique=False)
    op.drop_constraint('employee_feedbacks_to_employee_id_fkey', 'employee_feedbacks', type_='foreignkey')
    op.drop_constraint('employee_feedbacks_from_employee_id_fkey', 'employee_feedbacks', type_='foreignkey')
    op.create_foreign_key(None, 'employee_feedbacks', 'users', ['to_employee_id'], ['id'])
    op.create_foreign_key(None, 'employee_feedbacks', 'users', ['from_employee_id'], ['id'])
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.add_column('tasks', sa.Column('assigned_to', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('assigned_by', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('tasks', sa.Column('comments', sa.Text(), nullable=True))
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tasks', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_constraint('tasks_created_by_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_employee_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_by'], ['id'])
    op.drop_column('tasks', 'employee_id')
    op.drop_column('tasks', 'assigned_date')
    op.drop_column('tasks', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('assigned_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_employee_id_fkey', 'tasks', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tasks_created_by_fkey', 'tasks', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('tasks', 'due_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('tasks', 'comments')
    op.drop_column('tasks', 'tags')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'assigned_by')
    op.drop_column('tasks', 'assigned_to')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_constraint(None, 'employee_feedbacks', type_='foreignkey')
    op.drop_constraint(None, 'employee_feedbacks', type_='foreignkey')
    op.create_foreign_key('employee_feedbacks_from_employee_id_fkey', 'employee_feedbacks', 'employees', ['from_employee_id'], ['id'])
    op.create_foreign_key('employee_feedbacks_to_employee_id_fkey', 'employee_feedbacks', 'employees', ['to_employee_id'], ['id'])
    op.drop_index(op.f('ix_employee_feedbacks_id'), table_name='employee_feedbacks')
    op.create_table('folders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_confidential', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='folders_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='folders_pkey')
    )
    op.create_index('ix_folders_id', 'folders', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PRESENT', 'ABSENT', 'LATE', 'LEAVE', name='attendancestatus'), autoincrement=False, nullable=False),
    sa.Column('check_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('check_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name='attendance_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='attendance_pkey')
    )
    op.create_index('ix_attendance_id', 'attendance', ['id'], unique=False)
    # ### end Alembic commands ###
