"""recreate_tables

Revision ID: f75bde2679e3
Revises: 838d81288ea1
Create Date: 2025-04-24 16:07:07.128076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f75bde2679e3'
down_revision: Union[str, None] = '838d81288ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.drop_index('ix_payslips_id', table_name='payslips')
    op.drop_table('payslips')
    op.drop_index('ix_salary_components_id', table_name='salary_components')
    op.drop_table('salary_components')
    op.create_foreign_key(None, 'attendance', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document_folders', 'users', ['created_by'], ['id'])
    op.add_column('documents', sa.Column('title', sa.String(length=200), nullable=False))
    op.add_column('documents', sa.Column('description', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('file_type', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.alter_column('documents', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('documents_folder_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'document_folders', ['folder_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'])
    op.drop_column('documents', 'uploader_id')
    op.drop_column('documents', 'upload_date')
    op.drop_column('documents', 'name')
    op.drop_column('documents', 'type')
    op.drop_column('documents', 'url')
    op.create_foreign_key(None, 'employee_feedbacks', 'users', ['to_employee_id'], ['id'])
    op.create_foreign_key(None, 'employee_feedbacks', 'users', ['from_employee_id'], ['id'])
    op.create_foreign_key(None, 'leads', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'leave_balances', 'users', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'leave_requests', 'users', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'leave_requests', 'users', ['approved_by'], ['id'])
    op.add_column('milestones', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('milestones', sa.Column('status', sa.String(), nullable=False))
    op.create_foreign_key(None, 'milestones', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_column('milestones', 'achieved_date')
    op.drop_column('milestones', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('milestones', sa.Column('achieved_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.drop_column('milestones', 'status')
    op.drop_column('milestones', 'date')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_constraint(None, 'leave_balances', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'employee_feedbacks', type_='foreignkey')
    op.drop_constraint(None, 'employee_feedbacks', type_='foreignkey')
    op.add_column('documents', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('upload_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('uploader_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_folder_id_fkey', 'documents', 'document_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.alter_column('documents', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('documents', 'uploaded_by')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'description')
    op.drop_column('documents', 'title')
    op.drop_constraint(None, 'document_folders', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_table('salary_components',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('EARNING', 'DEDUCTION', name='componenttype'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_percentage', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='salary_components_pkey')
    )
    op.create_index('ix_salary_components_id', 'salary_components', ['id'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_earnings', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_deductions', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('components', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payslips_pkey')
    )
    op.create_index('ix_payslips_id', 'payslips', ['id'], unique=False)
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
